### PR TITLE
add option total to sru_search()

### PR DESCRIPTION
**Pull request by jorol**

### CODE REVIEW

**Comment by nics** [comment]
why did you also remove limit, isn't it still useful to control how to records are fetched in the background?

**Comment by jorol** [comment]
I wanted ˋtotalˋ in the first place but mixed up with ˋlimitˋ. My use case for this fix is to look up ids, names, places, etc. where I just get some records back in most cases. I‘m also a fan of leaving batch sizes to the SRU server. If you see a use for ˋlimitˋ I can add it with another commit.

**Comment by jorol** [comment]
added option *limit* with another commit.

**Comment by nics** [comment]
Giving total a default value will constrain every request to 10 records, default should be to fetch all records, no?

**Comment by jorol** [comment]
Fixed with new commit.

**Comment by nichtich** [comment]
This has been implemented, so closing the pull request

**Comment by jorol** [comment]
Option `total`and the change for the default of `limit` are not merged yet.

**Comment by nics** [comment]
@jorol released your changes as 0.429

**Pull request merged**
